#!/bin/bash
# Description: Customize Linux OS based on Nucleus build requirement
# OS_Cust_script.sh last modified on 21-Sep-2015
# NOTE: PLEASE FILL THE BELOW DETAILS BEFORE EXECUTING THE SCRIPT (IP only for ifcfg-bond0)

IP=
NETMASK=
HOSTNAME=
FQDN=

bonding()
{
if [ ! -f /etc/modprobe.d/bonding.conf ]; then
        touch /etc/modprobe.d/bonding.conf
        echo 'alias bond0 bonding' >> /etc/modprobe.d/bonding.conf
        else
        echo 'alias bond0 bonding' >> /etc/modprobe.d/bonding.conf
fi
}

eth()
{
echo $'DEVICE=eth0\nTYPE=Ethernet\n#UUID=\nONBOOT=yes\nBOOTPROTO=none\n#HWADDR=\nMASTER=bond0\nSLAVE=yes\nUSERCTL=no\nNM_CONTROLLED=no' > /etc/sysconfig/network-scripts/ifcfg-eth0
echo
echo $'DEVICE=eth4\nTYPE=Ethernet\n#UUID=\nONBOOT=yes\nBOOTPROTO=none\n#HWADDR=\nMASTER=bond0\nSLAVE=yes\nUSERCTL=no\nNM_CONTROLLED=no' > /etc/sysconfig/network-scripts/ifcfg-eth4
}


bond0()
{
if [ ! -f /etc/sysconfig/network-scripts/ifcfg-bond0 ]; then
        touch /etc/sysconfig/network-scripts/ifcfg-bond0
        echo -e "DEVICE=bond0\nTYPE=Ethernet\n#UUID=\nIPADDR=${IP}\nNETMASK=${NETMASK}\nDEFROUTE=yes\nONBOOT=yes\nBOOTPROTO=none\nUSERCTL=no\nNM_CONTROLLED=no\nMTU=1408\nIPV6INIT=no\nBONDING_OPTS=\"mode=1 miimon=100\"" > /etc/sysconfig/network-scripts/ifcfg-bond0
else
        echo -e "DEVICE=bond0\nTYPE=Ethernet\n#UUID=\nIPADDR=${IP}\nNETMASK=${NETMASK}\nDEFROUTE=yes\nONBOOT=yes\nBOOTPROTO=none\nUSERCTL=no\nNM_CONTROLLED=no\nMTU=1408\nIPV6INIT=no\nBONDING_OPTS=\"mode=1 miimon=100\"" > /etc/sysconfig/network-scripts/ifcfg-bond0
fi
}

dis_ipv6()
{
if grep NETWORKING_IPV6=yes /etc/sysconfig/network
        then
                sed -i '/NETWORKING_IPV6=yes/c\NETWORKING_IPV6=no' /etc/sysconfig/network
        elif grep NETWORKING_IPV6=no /etc/sysconfig/network
then
        :
else
                echo "NETWORKING_IPV6=no" >> /etc/sysconfig/network

fi
}

host_name()
{
        echo "${IP}     ${HOSTNAME} ${FQDN}" >> /etc/hosts
}

resolv_conf()
{
        echo $'#Generated by NetworkManager\nsearch mgt.dbn.hpe.com\nnameserver 172.18.40.233\nnameserver 172.18.40.234\nnameserver 172.18.40.125\nnameserver 172.18.40.126\nnameserver 172.18.40.134' >> /etc/resolv.conf
}

dis_selinux()
{
if grep SELINUX=enforcing /etc/selinux/config
        then
                sed -i '/SELINUX=enforcing/c\SELINUX=disabled' /etc/selinux/config
        elif grep SELINUX=disabled /etc/selinux/config
then
        :
fi
}

dis_iptables()
{
        /etc/init.d/iptables save
        /etc/init.d/iptables stop
        chkconfig iptables off
}

NIC_conf()
{
        echo "net.ipv4.ip_no_pmtu_disc=0" >> /etc/sysctl.conf
        echo "MTU=1408" >> /etc/sysconfig/network-scripts/ifcfg-eth0
        echo "MTU=1408" >> /etc/sysconfig/network-scripts/ifcfg-eth1
}

services()
{
	service network restart
}


#CALLING FUNCTION

bonding
eth
bond0
dis_ipv6
host_name
resolv_conf
dis_selinux
dis_iptables
NIC_conf
services
